apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: ["http://172.17.0.2:31200"]
    
---
# this is metricbeat deployment
# expose two port.8080(http)->31808
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jeff-logstash
spec:
  selector:
    matchLabels:
      app: jeff-logstash
  replicas: 1 
  template:
    metadata:
      labels:
        app: jeff-logstash
    spec:
      hostNetwork: false
      volumes:
       - name:  logstash-config
         configMap:
          name:  logstash-config      
      containers:
        - image: "logstash:7.8.1"
          name: jeff-logstash
          volumeMounts:
          - name: logstash-config
            mountPath: "/usr/share/logstash/config/logstash.yml"            
            subPath: logstash.yml    
          
