apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |- 
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://172.17.0.2:31200" ]
    monitoring.ui.container.elasticsearch.enabled: true   

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jeff-elasticsearch
spec:
  selector:
    matchLabels:
      app: jeff-elasticsearch
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: jeff-elasticsearch
    spec:
      containers:
        - name: jeff-elasticsearch
          image: elasticsearch:7.8.1
          ports:
            - containerPort: 9300
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: jeff-elasticsearch
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: jeff-elasticsearch
  ports:
    - name: http
      port: 9200
      nodePort: 31200
    - name: tcp
      port: 9300
      nodePort: 31300      
  type: NodePort            
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jeff-kibana
spec:
  selector:
    matchLabels:
      app: jeff-kibana
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: jeff-kibana
    spec:
      containers:
        - name: jeff-kibana
          image: kibana:7.8.1
          ports:
            - containerPort: 5601
          volumeMounts:
            - name:  kibana-config
              mountPath:  /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name:  kibana-config
          configMap:
            name: kibana-config
              
---
apiVersion: v1
kind: Service
metadata:
  name: jeff-kibana
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: jeff-kibana
  ports:
    - name: http
      port: 5601
      nodePort: 31601
  type: NodePort              