#Come from https://raw.githubusercontent.com/cocowool/k8s-go/master/elk/elk-single.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-single
spec:
  selector:
    matchLabels:
      app: filebeat-single
  replicas: 1
  template:
    metadata:
      name: filebeat-single
      labels:
        app: filebeat-single
    spec:
      containers:
      - image: docker.elastic.co/beats/filebeat:7.8.1
        name: filebeat-single

