---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jeff-lasticsearch
spec:
  selector:
    matchLabels:
      app: jeff-lasticsearch
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: jeff-lasticsearch
    spec:
      containers:
        - name: jeff-lasticsearch
          image: elasticsearch:7.8.1
          ports:
            - containerPort: 9300
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: jeff-lasticsearch
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: jeff-lasticsearch
  ports:
    - name: http
      port: 9200
      nodePort: 31200
    - name: tcp
      port: 9300
      nodePort: 31300      
  type: NodePort            